const APPLICATIONS = {
  HOME: `HOME`,
  ABOUT_US: `ABOUT_US`,
  CASE_STUDIES: "CASE_STUDIES",
  CAREER: "CAREER",
  CONTACT_US: "CONTACT_US",
  PRIVACY_POLICY: "PRIVACY_POLICY",
  TERMS_AND_CONDITIONS: "TERMS_AND_CONDITIONS",
  COOKIE_POLICY: "COOKIE_POLICY",
  REFUND_POLICY: "REFUND_POLICY",
  PAGE_NOT_FOUND: "PAGE_NOT_FOUND",
} as const;

type TApplications = (typeof APPLICATIONS)[keyof typeof APPLICATIONS];

const APPLICATION_URLS: Record<TApplications, string> = {
  [APPLICATIONS.HOME]: `/`,
  [APPLICATIONS.ABOUT_US]: `/about-us`,
  [APPLICATIONS.CASE_STUDIES]: `/case-studies/*`,
  [APPLICATIONS.CAREER]: "/career",
  [APPLICATIONS.CONTACT_US]: "/contact-us",
  [APPLICATIONS.PRIVACY_POLICY]: "/privacy-policy",
  [APPLICATIONS.COOKIE_POLICY]: "/cookie-policy",
  [APPLICATIONS.REFUND_POLICY]: "/refund-policy",
  [APPLICATIONS.TERMS_AND_CONDITIONS]: "/terms-and-conditions",
  [APPLICATIONS.PAGE_NOT_FOUND]: "*",
};

export { APPLICATIONS, APPLICATION_URLS };
